<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Impute Missing Values**

Estimated time needed: **30** minutes

In this lab, you will practice essential data wrangling techniques using the Stack Overflow survey dataset. The primary focus is on handling missing data and ensuring data quality. You will:

- **Load the Data:** Import the dataset into a DataFrame using the pandas library.

- **Clean the Data:** Identify and remove duplicate entries to maintain data integrity.

- **Handle Missing Values:** Detect missing values, impute them with appropriate strategies, and verify the imputation to create a complete and reliable dataset for analysis.

This lab equips you with the skills to effectively preprocess and clean real-world datasets, a crucial step in any data analysis project.

## Objectives

In this lab, you will perform the following:

-   Identify missing values in the dataset.

-   Apply techniques to impute missing values in the dataset.
  
-   Use suitable techniques to normalize data in the dataset.

-----

#### Install needed library

In [3]:
!pip install pandas

Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 138.7 MB/s eta 0:00:00
Downloading numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 153.9 MB/s eta 0:00:00
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]

### Step 1: Import Required Libraries

In [4]:
import pandas as pd

### Step 2: Load the Dataset Into a Dataframe

#### **Read Data**
<p>
The functions below will download the dataset into your browser:
</p>

In [5]:
file_path ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/UDKAZw-kz18Yj8P6icf_qw/survey-data-duplicates.csv"
df = pd.read_csv(file_path)

# Display the first few rows to ensure it loaded correctly
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

### Step 3. Finding and Removing Duplicates
##### Task 1: Identify duplicate rows in the dataset.

In [6]:
duplicates = df[df.duplicated()]
print(duplicates)

       ResponseId                                         MainBranch  \
65437           1                     I am a developer by profession
65438           2                     I am a developer by profession
65439           3                     I am a developer by profession
65440           4                              I am learning to code
65441           5                     I am a developer by profession
65442           6                        I code primarily as a hobby
65443           7  I am not primarily a developer, but I write co...
65444           8                              I am learning to code
65445           9                        I code primarily as a hobby
65446          10                     I am a developer by profession

                      Age                                         Employment  \
65437  Under 18 years old                                Employed, full-time
65438     35-44 years old                                Employed, full-time
65439     45-54 years old                                Employed, full-time
65440     18-24 years old                                 Student, full-time
65441     18-24 years old                                 Student, full-time
65442  Under 18 years old                                 Student, full-time
65443     35-44 years old                                Employed, full-time
65444     18-24 years old  Student, full-time;Not employed, but looking f...
65445     45-54 years old                                Employed, full-time
65446     35-44 years old  Independent contractor, freelancer, or self-em...

      RemoteWork   Check                                   CodingActivities  \
65437     Remote  Apples                                              Hobby
65438     Remote  Apples  Hobby;Contribute to open-source projects;Other...
65439     Remote  Apples  Hobby;Contribute to open-source projects;Other...
65440        NaN  Apples                                                NaN
65441        NaN  Apples                                                NaN
65442        NaN  Apples                                                NaN
65443     Remote  Apples                       I don’t code outside of work
65444        NaN  Apples                                                NaN
65445  In-person  Apples                                              Hobby
65446     Remote  Apples                           Bootstrapping a business

                                                 EdLevel  \
65437                          Primary/elementary school
65438       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65439    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
65440  Some college/university study without earning ...
65441  Secondary school (e.g. American high school, G...
65442                          Primary/elementary school
65443     Professional degree (JD, MD, Ph.D, Ed.D, etc.)
65444  Secondary school (e.g. American high school, G...
65445     Professional degree (JD, MD, Ph.D, Ed.D, etc.)
65446    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

                                               LearnCode  \
65437                             Books / Physical media
65438  Books / Physical media;Colleague;On the job tr...
65439  Books / Physical media;Colleague;On the job tr...
65440  Other online resources (e.g., videos, blogs, f...
65441  Other online resources (e.g., videos, blogs, f...
65442  School (i.e., University, College, etc);Online...
65443  Other online resources (e.g., videos, blogs, f...
65444  Other online resources (e.g., videos, blogs, f...
65445  Books / Physical media;Other online resources ...
65446  On the job training;Other online resources (e....

                                         LearnCodeOnline  ... JobSatPoints_6  \
65437                                                NaN  ...            NaN
65438  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
65439  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
65440  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
65441  Technical documentation;Blogs;Written Tutorial...  ...            NaN
65442                                                NaN  ...            NaN
65443  Technical documentation;Stack Overflow;Written...  ...            NaN
65444  Technical documentation;Video-based Online Cou...  ...            NaN
65445        Stack Overflow;Written-based Online Courses  ...            NaN
65446  Technical documentation;Blogs;Written Tutorial...  ...            NaN

      JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
65437            NaN            NaN            NaN             NaN
65438            0.0            0.0            0.0             0.0
65439            NaN            NaN            NaN             NaN
65440            NaN            NaN            NaN             NaN
65441            NaN            NaN            NaN             NaN
65442            NaN            NaN            NaN             NaN
65443            NaN            NaN            NaN             NaN
65444            NaN            NaN            NaN             NaN
65445            NaN            NaN            NaN             NaN
65446            NaN            NaN            NaN             NaN

      JobSatPoints_11           SurveyLength                  SurveyEase  \
65437             NaN                    NaN                         NaN
65438             0.0                    NaN                         NaN
65439             NaN  Appropriate in length                        Easy
65440             NaN               Too long                        Easy
65441             NaN              Too short                        Easy
65442             NaN  Appropriate in length                        Easy
65443             NaN               Too long  Neither easy nor difficult
65444             NaN  Appropriate in length                   Difficult
65445             NaN  Appropriate in length  Neither easy nor difficult
65446             NaN               Too long                        Easy

      ConvertedCompYearly JobSat
65437                 NaN    NaN
65438                 NaN    NaN
65439                 NaN    NaN
65440                 NaN    NaN
65441                 NaN    NaN
65442                 NaN    NaN
65443                 NaN    NaN
65444                 NaN    NaN
65445                 NaN    NaN
65446                 NaN    NaN

[10 rows x 114 columns]

##### Task 2: Remove the duplicate rows from the dataframe.

In [7]:
df.drop_duplicates(inplace=True)

### Step 4: Finding Missing Values
##### Task 3: Find the missing values for all columns.

In [8]:
missing_data = df.isnull()

for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

ResponseId
ResponseId
False    65437
Name: count, dtype: int64

MainBranch
MainBranch
False    65437
Name: count, dtype: int64

Age
Age
False    65437
Name: count, dtype: int64

Employment
Employment
False    65437
Name: count, dtype: int64

RemoteWork
RemoteWork
False    54806
True     10631
Name: count, dtype: int64

Check
Check
False    65437
Name: count, dtype: int64

CodingActivities
CodingActivities
False    54466
True     10971
Name: count, dtype: int64

EdLevel
EdLevel
False    60784
True      4653
Name: count, dtype: int64

LearnCode
LearnCode
False    60488
True      4949
Name: count, dtype: int64

LearnCodeOnline
LearnCodeOnline
False    49237
True     16200
Name: count, dtype: int64

TechDoc
TechDoc
False    40897
True     24540
Name: count, dtype: int64

YearsCode
YearsCode
False    59869
True      5568
Name: count, dtype: int64

YearsCodePro
YearsCodePro
False    51610
True     13827
Name: count, dtype: int64

DevType
DevType
False    59445
True      5992
Name: count, dtype: int64

OrgSize
OrgSize
False    47480
True     17957
Name: count, dtype: int64

PurchaseInfluence
PurchaseInfluence
False    47406
True     18031
Name: count, dtype: int64

BuyNewTool
BuyNewTool
False    45181
True     20256
Name: count, dtype: int64

BuildvsBuy
BuildvsBuy
False    43358
True     22079
Name: count, dtype: int64

TechEndorse
TechEndorse
False    43668
True     21769
Name: count, dtype: int64

Country
Country
False    58930
True      6507
Name: count, dtype: int64

Currency
Currency
False    46684
True     18753
Name: count, dtype: int64

CompTotal
CompTotal
False    33740
True     31697
Name: count, dtype: int64

LanguageHaveWorkedWith
LanguageHaveWorkedWith
False    59745
True      5692
Name: count, dtype: int64

LanguageWantToWorkWith
LanguageWantToWorkWith
False    55752
True      9685
Name: count, dtype: int64

LanguageAdmired
LanguageAdmired
False    50872
True     14565
Name: count, dtype: int64

DatabaseHaveWorkedWith
DatabaseHaveWorkedWith
False    50254
True     15183
Name: count, dtype: int64

DatabaseWantToWorkWith
DatabaseWantToWorkWith
False    42558
True     22879
Name: count, dtype: int64

DatabaseAdmired
DatabaseAdmired
False    38557
True     26880
Name: count, dtype: int64

PlatformHaveWorkedWith
PlatformHaveWorkedWith
False    42366
True     23071
Name: count, dtype: int64

PlatformWantToWorkWith
PlatformWantToWorkWith
False    34532
True     30905
Name: count, dtype: int64

PlatformAdmired
PlatformAdmired
True     34060
False    31377
Name: count, dtype: int64

WebframeHaveWorkedWith
WebframeHaveWorkedWith
False    45161
True     20276
Name: count, dtype: int64

WebframeWantToWorkWith
WebframeWantToWorkWith
False    38535
True     26902
Name: count, dtype: int64

WebframeAdmired
WebframeAdmired
False    34943
True     30494
Name: count, dtype: int64

EmbeddedHaveWorkedWith
EmbeddedHaveWorkedWith
True     43223
False    22214
Name: count, dtype: int64

EmbeddedWantToWorkWith
EmbeddedWantToWorkWith
True     47837
False    17600
Name: count, dtype: int64

EmbeddedAdmired
EmbeddedAdmired
True     48704
False    16733
Name: count, dtype: int64

MiscTechHaveWorkedWith
MiscTechHaveWorkedWith
False    39443
True     25994
Name: count, dtype: int64

MiscTechWantToWorkWith
MiscTechWantToWorkWith
False    32964
True     32473
Name: count, dtype: int64

MiscTechAdmired
MiscTechAdmired
True     35841
False    29596
Name: count, dtype: int64

ToolsTechHaveWorkedWith
ToolsTechHaveWorkedWith
False    52482
True     12955
Name: count, dtype: int64

ToolsTechWantToWorkWith
ToolsTechWantToWorkWith
False    46084
True     19353
Name: count, dtype: int64

ToolsTechAdmired
ToolsTechAdmired
False    43997
True     21440
Name: count, dtype: int64

NEWCollabToolsHaveWorkedWith
NEWCollabToolsHaveWorkedWith
False    57592
True      7845
Name: count, dtype: int64

NEWCollabToolsWantToWorkWith
NEWCollabToolsWantToWorkWith
False    52087
True     13350
Name: count, dtype: int64

NEWCollabToolsAdmired
NEWCollabToolsAdmired
False    50711
True     14726
Name: count, dtype: int64

OpSysPersonal use
OpSysPersonal use
False    58174
True      7263
Name: count, dtype: int64

OpSysProfessional use
OpSysProfessional use
False    52973
True     12464
Name: count, dtype: int64

OfficeStackAsyncHaveWorkedWith
OfficeStackAsyncHaveWorkedWith
False    48093
True     17344
Name: count, dtype: int64

OfficeStackAsyncWantToWorkWith
OfficeStackAsyncWantToWorkWith
False    38966
True     26471
Name: count, dtype: int64

OfficeStackAsyncAdmired
OfficeStackAsyncAdmired
False    37204
True     28233
Name: count, dtype: int64

OfficeStackSyncHaveWorkedWith
OfficeStackSyncHaveWorkedWith
False    55545
True      9892
Name: count, dtype: int64

OfficeStackSyncWantToWorkWith
OfficeStackSyncWantToWorkWith
False    46711
True     18726
Name: count, dtype: int64

OfficeStackSyncAdmired
OfficeStackSyncAdmired
False    44712
True     20725
Name: count, dtype: int64

AISearchDevHaveWorkedWith
AISearchDevHaveWorkedWith
False    44453
True     20984
Name: count, dtype: int64

AISearchDevWantToWorkWith
AISearchDevWantToWorkWith
False    36701
True     28736
Name: count, dtype: int64

AISearchDevAdmired
AISearchDevAdmired
False    35543
True     29894
Name: count, dtype: int64

NEWSOSites
NEWSOSites
False    60286
True      5151
Name: count, dtype: int64

SOVisitFreq
SOVisitFreq
False    59536
True      5901
Name: count, dtype: int64

SOAccount
SOAccount
False    59560
True      5877
Name: count, dtype: int64

SOPartFreq
SOPartFreq
False    45237
True     20200
Name: count, dtype: int64

SOHow
SOHow
False    58962
True      6475
Name: count, dtype: int64

SOComm
SOComm
False    59163
True      6274
Name: count, dtype: int64

AISelect
AISelect
False    60907
True      4530
Name: count, dtype: int64

AISent
AISent
False    45873
True     19564
Name: count, dtype: int64

AIBen
AIBen
False    36894
True     28543
Name: count, dtype: int64

AIAcc
AIAcc
False    37302
True     28135
Name: count, dtype: int64

AIComplex
AIComplex
False    37021
True     28416
Name: count, dtype: int64

AIToolCurrently Using
AIToolCurrently Using
False    35072
True     30365
Name: count, dtype: int64

AIToolInterested in Using
AIToolInterested in Using
True     34746
False    30691
Name: count, dtype: int64

AIToolNot interested in Using
AIToolNot interested in Using
True     41023
False    24414
Name: count, dtype: int64

AINextMuch more integrated
AINextMuch more integrated
True     51999
False    13438
Name: count, dtype: int64

AINextNo change
AINextNo change
True     52939
False    12498
Name: count, dtype: int64

AINextMore integrated
AINextMore integrated
True     41009
False    24428
Name: count, dtype: int64

AINextLess integrated
AINextLess integrated
True     63082
False     2355
Name: count, dtype: int64

AINextMuch less integrated
AINextMuch less integrated
True     64289
False     1148
Name: count, dtype: int64

AIThreat
AIThreat
False    44689
True     20748
Name: count, dtype: int64

AIEthics
AIEthics
False    41548
True     23889
Name: count, dtype: int64

AIChallenges
AIChallenges
False    37531
True     27906
Name: count, dtype: int64

TBranch
TBranch
False    44477
True     20960
Name: count, dtype: int64

ICorPM
ICorPM
True     35636
False    29801
Name: count, dtype: int64

WorkExp
WorkExp
True     35779
False    29658
Name: count, dtype: int64

Knowledge_1
Knowledge_1
True     36773
False    28664
Name: count, dtype: int64

Knowledge_2
Knowledge_2
True     37416
False    28021
Name: count, dtype: int64

Knowledge_3
Knowledge_3
True     37342
False    28095
Name: count, dtype: int64

Knowledge_4
Knowledge_4
True     37407
False    28030
Name: count, dtype: int64

Knowledge_5
Knowledge_5
True     37557
False    27880
Name: count, dtype: int64

Knowledge_6
Knowledge_6
True     37573
False    27864
Name: count, dtype: int64

Knowledge_7
Knowledge_7
True     37659
False    27778
Name: count, dtype: int64

Knowledge_8
Knowledge_8
True     37679
False    27758
Name: count, dtype: int64

Knowledge_9
Knowledge_9
True     37802
False    27635
Name: count, dtype: int64

Frequency_1
Frequency_1
True     37068
False    28369
Name: count, dtype: int64

Frequency_2
Frequency_2
True     37073
False    28364
Name: count, dtype: int64

Frequency_3
Frequency_3
True     37727
False    27710
Name: count, dtype: int64

TimeSearching
TimeSearching
True     36526
False    28911
Name: count, dtype: int64

TimeAnswering
TimeAnswering
True     36593
False    28844
Name: count, dtype: int64

Frustration
Frustration
True     37186
False    28251
Name: count, dtype: int64

ProfessionalTech
ProfessionalTech
True     37673
False    27764
Name: count, dtype: int64

ProfessionalCloud
ProfessionalCloud
True     36946
False    28491
Name: count, dtype: int64

ProfessionalQuestion
ProfessionalQuestion
True     36630
False    28807
Name: count, dtype: int64

Industry
Industry
True     36579
False    28858
Name: count, dtype: int64

JobSatPoints_1
JobSatPoints_1
True     36113
False    29324
Name: count, dtype: int64

JobSatPoints_4
JobSatPoints_4
True     36044
False    29393
Name: count, dtype: int64

JobSatPoints_5
JobSatPoints_5
True     36026
False    29411
Name: count, dtype: int64

JobSatPoints_6
JobSatPoints_6
True     35987
False    29450
Name: count, dtype: int64

JobSatPoints_7
JobSatPoints_7
True     35989
False    29448
Name: count, dtype: int64

JobSatPoints_8
JobSatPoints_8
True     35981
False    29456
Name: count, dtype: int64

JobSatPoints_9
JobSatPoints_9
True     35981
False    29456
Name: count, dtype: int64

JobSatPoints_10
JobSatPoints_10
True     35987
False    29450
Name: count, dtype: int64

JobSatPoints_11
JobSatPoints_11
True     35992
False    29445
Name: count, dtype: int64

SurveyLength
SurveyLength
False    56182
True      9255
Name: count, dtype: int64

SurveyEase
SurveyEase
False    56238
True      9199
Name: count, dtype: int64

ConvertedCompYearly
ConvertedCompYearly
True     42002
False    23435
Name: count, dtype: int64

JobSat
JobSat
True     36311
False    29126
Name: count, dtype: int64

##### Task 4: Find out how many rows are missing in the column RemoteWork.

In [9]:
df['RemoteWork'].isna().sum()

np.int64(10631)

### Step 5. Imputing Missing Values
##### Task 5: Find the value counts for the column RemoteWork.

In [17]:
df['RemoteWork'].value_counts()

RemoteWork
Hybrid (some remote, some in-person)    33646
Remote                                  20831
In-person                               10960
Name: count, dtype: int64

##### Task 6: Identify the most frequent (majority) value in the RemoteWork column.

In [11]:
majority_value = df['RemoteWork'].mode()[0]
print(majority_value)

Hybrid (some remote, some in-person)

##### Task 7: Impute (replace) all the empty rows in the column RemoteWork with the majority value.

In [14]:
majority_value = df['RemoteWork'].mode()[0]
df['RemoteWork'] = df['RemoteWork'].fillna(majority_value)

##### Task 8: Check for any compensation-related columns and describe their distribution.

In [20]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       ...
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9',
       'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
       'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=114)

In [21]:
df['CompTotal'].unique()

array([     nan, 2040000.,   28000., ...,  254600.,  247433.,   77700.],
      shape=(3338,))

In [22]:
df['CompTotal'].value_counts()

CompTotal
100000.0     939
60000.0      839
120000.0     793
80000.0      728
50000.0      705
            ...
3087958.0      1
2520.0         1
254600.0       1
247433.0       1
77700.0        1
Name: count, Length: 3337, dtype: int64

In [26]:
def conditions(s):
  if (s['CompTotal'] == 'Yearly'):
    return s['CompTotal']
  elif (s['CompTotal'] == 'Monthly'):
    return (s['CompTotal'] * 12)  
  else:
    return (s['CompTotal'] * 52)

In [27]:
df['ConvertedCompYearly'] = df.apply(conditions, axis=1)
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time","Hybrid (some remote, some in-person)",Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time","Hybrid (some remote, some in-person)",Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [28]:
df[['CompTotal', 'ConvertedCompYearly']].head()

   CompTotal  ConvertedCompYearly
0        NaN                  NaN
1        NaN                  NaN
2        NaN                  NaN
3        NaN                  NaN
4        NaN                  NaN

In [29]:
df['ConvertedCompYearly'].describe()

count     3.374000e+04
mean     1.541197e+147
std      2.830941e+149
min       0.000000e+00
25%       3.120000e+06
50%       5.720000e+06
75%       1.300000e+07
max      5.200000e+151
Name: ConvertedCompYearly, dtype: float64

### Summary

**In this lab, you focused on imputing missing values in the dataset.**

- Use the <code>pandas.read_csv()</code> function to load a dataset from a CSV file into a DataFrame.

- Download the dataset if it's not available online and specify the correct file path.

<!--
## Change Log
|Date (YYYY-MM-DD)|Version|Changed By|Change Description|
|-|-|-|-|
|2024-11-05|1.3|Madhusudhan Moole|Updated lab|
|2024-10-29|1.2|Madhusudhan Moole|Updated lab|
|2024-09-27|1.1|Madhusudhan Moole|Updated lab|
|2024-09-26|1.0|Raghul Ramesh|Created lab|
--!>

Copyright © IBM Corporation. All rights reserved.